### PR TITLE
Add HDFS example

### PR DESCRIPTION
**Pull request by bokket**
Signed-off-by: bokket <3100563328@qq.com>

### CODE REVIEW

**Comment by bokket** [comment]
Now hdfs did not do the test on top of win :)

**Comment by Xuanwo** [comment]
There no tests logic in go-storage-example, maybe a random CI error, Let's try restart it.

**Comment by Xuanwo** [comment]
We failed at `go mod verify`

**Comment by Xuanwo** [comment]
Well, I got it, the `go.sum` is not updated correctly. Do you have run `make build` before sending PRs?

**Comment by bokket** [comment]
> Well, I got it, the `go.sum` is not updated correctly. Do you have run `make build` before sending PRs?

nope，I will re-execute it

**Comment by Xuanwo** [comment]
Please try to bump hdfs to version 0.2.0 for a test.

**Comment by Xuanwo** [comment]
Please try https://github.com/beyondstorage/go-service-hdfs/releases/tag/v0.2.1 instead.

<blockquote><div> GitHub</div><div><strong><a href="/beyondstorage/go-service-hdfs/releases/tag/v0.2.1">Release v0.2.1 · beyondstorage/go-service-hdfs</a></strong></div><div>v0.2.1 - 2021-09-09
Fixed

Fix extra space in CHANGELOG.md which will lead to go mod verify failed.</div></blockquote>

**Review by Xuanwo — APPROVED** [review]

**Pull request merged**
